### ISSUE TITLE
Getting Module 'platanus.inflector' is not available

### ISSUE THREAD

**Issue by marlonmantilla** [lykmapipo/ngData#19]
Hey guys, getting this error:

```
Uncaught Error: [$injector:modulerr] Failed to instantiate module app due to:
Error: [$injector:modulerr] Failed to instantiate module ngData due to:
Error: [$injector:modulerr] Failed to instantiate module platanus.inflector due to:
Error: [$injector:nomod] Module 'platanus.inflector' is not available! You either misspelled the     module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
 http://errors.angularjs.org/1.4.3/$injector/nomod?p0=platanus.inflector
at http://localhost:8100/lib/ionic/js/ionic.bundle.js:13380:12
at http://localhost:8100/lib/ionic/js/ionic.bundle.js:15270:17
at ensure (http://localhost:8100/lib/ionic/js/ionic.bundle.js:15194:38)
at module (http://localhost:8100/lib/ionic/js/ionic.bundle.js:15268:14)
at http://localhost:8100/lib/ionic/js/ionic.bundle.js:17674:22
at forEach (http://localhost:8100/lib/ionic/js/ionic.bundle.js:13648:20)
at loadModules (http://localhost:8100/lib/ionic/js/ionic.bundle.js:17658:5)
at http://localhost:8100/lib/ionic/js/ionic.bundle.js:17675:40
at forEach (http://localhost:8100/lib/ionic/js/ionic.bundle.js:13648:20)
at loadModules (http://localhost:8100/lib/ionic/js/ionic.bundle.js:17658:5)
```

My bower.json looks like this:

```
{
  "name": "HelloIonic",
  "private": "true",
  "devDependencies": {
    "ionic": "driftyco/ionic-bower#1.2.4"
  },
 "dependencies": {
   "restangular": "1.5.2",
   "lodash": "3.10.1",
   "ngstorage": "0.3.11",
   "ngData": "0.2.0",
   "angular-inflector": "0.2.0"
  },
  "resolutions": {
    "angular": "1.4.12"
  }
}
```

**Comment by hrwtz** [comment]
There are a few dependencies which you need to include, so make sure they're all loaded:

`angular, angular-inflector, lodash, squel, validate`
